[project]
name = "poetry_test"
description = ""
version = "0.1.0"

[project.optional-dependencies]
full = [
    "module1",
    "module2"
]
module1 = [
    "module1"
]
module2 = [
    "module2"
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
