[tool.poetry]
name = "module2"
version = "0.1.0"
description = ""
authors = ["Tomasz Rymkiewicz <kreha1@pm.me>"]
packages = [
    { include = "*" }
]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
